name: CI

on:
  push:
    branches: [ master ]
    tags: [ v* ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build CLI application
        run: ./gradlew :cli:shadowJar -x test
      - name: Test
        run: ./gradlew :core:test
      - name: Change ownership of core build directory
        run: sudo chown -R $(id -u):$(id -g) ${{ github.workspace }}/core/build
      - name: Report test results
        uses: ashley-taylor/junit-report-annotations-action@master
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "${{ github.workspace }}/core/build/test-results/test/*.xml"
        if: always()
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 8
          graalvm-version: 21.1.0
          native-image: true
      - name: Build Docker image
        run: ./gradlew :docker:nativeBuild -x test
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: JServe
          path: ${{ github.workspace }}/cli/build/libs/*.jar
